### ISSUE TITLE
Update titles and descriptions

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.TagHelpers#11]
According to [ASP.NET 5 is dead - Introducing ASP.NET Core 1.0 and .NET Core 1.0](http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx)

- [x] README
- [x] Wiki pages
- [x] Package metadata

**Comment by IlyaKhD** [comment]
This announcement contains more details: https://github.com/aspnet/Announcements/issues/144.
