### ISSUE TITLE
Scheduler sample - data loading error (500)

### ISSUE THREAD

**Issue by San4es** [DevExpress/DevExtreme.AspNet.TagHelpers#16]
The following request fails:
http://localhost:51539/GoogleCalendar/Appointments?filter=%5B%5Bnull%5D%5D
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

**Comment by AlekseyMartynov** [comment]
@San4es 
Let's debug together tomorrow.
Cannot reproduce on my side.

**Comment by AlekseyMartynov** [comment]
@San4es 
My fault: forgot to update bower packages.
