### ISSUE TITLE
bind grid datasource in angular

### ISSUE THREAD

**Issue by apoutney** [DevExpress/DevExtreme.AspNet.TagHelpers#20]
I have an array of objects in my angular controller that I want to use as the datasource for my grid

How can I bind this array using the tag helpers

`<dx-data-grid>
        <datasource items="{{dataSource}}" />
</dx-data-grid>`

doesnt seem to work

**Comment by AlekseyMartynov** [comment]
@apoutney 
Tag helper attributes accept server-side (C#) values, and are unaware of JavaScript contexts. To assign a client-side data source (or any other option), use techniques described in the [Use JavaScript with TagHelpers wiki page](https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/wiki/Use-JavaScript-with-TagHelpers-(Event-Handlers,-Templates,-etc))
