### ISSUE TITLE
Whats the status of this?

### ISSUE THREAD

**Issue by Se3ker** [DevExpress/DevExtreme.AspNet.TagHelpers#26]
Hi,

whats the current status of DevExtreme TagHelpers, will it be ready for Asp.Net Core 1.0 release, and to what extent?

**Comment by AlekseyMartynov** [comment]
Hi @Se3ker 

The project has been published with the "Release Candidate" status. It's ready for use today (with RC1 release of ASP.NET Core), and we'll continue to update source code and NuGet packages for RC2 and RTM too.

**Comment by Se3ker** [comment]
Ok, but there's only 6 or 7 helpers now? Im using DevExtreme bower package and NuGet TagHelpers package, is that correct, or do I need to install from this link to get all the widgets?
https://go.devexpress.com/DevExpressDownload_DevExtremeCompleteTrial.aspx

If this is all there is at the moment, will full DevExtreme be ready for Core 1.0 release?

**Comment by AlekseyMartynov** [comment]
> there's only 6 or 7 helpers now

That's right, currently we provide tag helpers for the most complex components (Data Grid, Charts, Scheduler). Other widgets can be added to views using the jQuery approach (check the [related docs](http://js.devexpress.com/Documentation/Tutorial/UI_Widgets/Add_Widget_to_MVC_Project/?version=15_2#Add_a_DevExtreme_Widget)).

> will full DevExtreme be ready for Core 1.0 release?

Though there's no public roadmap for DevExtreme, I can tell that the team is actively working on better integration with ASP.NET MVC. Stay tuned and subscribe to our blogs at https://community.devexpress.com/Blogs/
