### ISSUE TITLE
DataGrid not working properly after RC2 upgrade

### ISSUE THREAD

**Issue by Se3ker** [DevExpress/DevExtreme.AspNet.TagHelpers#29]
DataGrid appears to not load data correctly and keeps data in session.

When I create new records, it doesn't load them, even after page refresh, it loads on sorting and paging but incorrectly and seemingly random. Even if I go to database and delete records manually it keeps showing the same records up until I close the browser and end the session.

Normal DataGrid TagHelper usage as per documentation
```
<dx-data-grid>
    <datasource controller="Vendors" load-action="GetVendors" />    
    <group-panel visible="true" />
    <filter-row visible="true" />
</dx-data-grid>
```
Controller
```
        [HttpGet]
        public async Task<Object> GetVendors([DataSourceLoadOptions]DataSourceLoadOptions loadOptions)
        {
            ApplicationUser user = await _userManager.GetUserAsync(HttpContext.User);
            List<Vendor> vendors = await _context.Vendors
                .Where(v => v.CompanyId == user.CompanyId)
                .ToListAsync();
            return DataSourceLoader.Load(vendors, loadOptions);
        }
```
Video Demo
https://onedrive.live.com/redir?resid=529CD01DE6BFCFDD!299&authkey=!AK5xe-zQrQJRC0s&ithint=file%2cswf

**Comment by AlekseyMartynov** [comment]
@Se3ker at first glance, it looks like an HTTP caching issue.

Please check if adding the following `onBeforeSend` handler helps:
```
<datasource on-before-send="function(op, ajaxSettings) { ajaxSettings.cache = false }">
```

**Comment by Se3ker** [comment]
Yes that fixes it. Works now as expected.

**Comment by AlekseyMartynov** [comment]
Thank you for your help in debugging the case. We'll add cache-busting to the Data library script (ticket: https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/59).

In the meantime, use the `onBeforeSend` workaround.
