### ISSUE TITLE
DataGrid wierd errors

### ISSUE THREAD

**Issue by Se3ker** [DevExpress/DevExtreme.AspNet.TagHelpers#31]
Hi, there are still errors while using the datagrid:

1. column datatypes not correctly rendered based on entity model types - changing property order in class fixes it. specifically the two Boolean fields, one gets rendered in datagrid as bool, the other doesent.

Works:
```
        public bool IsPurchasedItem { get; set; }

        public ICollection<PurchaseItem> PurchaseItems { get; set; }

        public bool IsTrackedInInventory { get; set; }

        public int ItemGroupId { get; set; }
        public ItemGroup ItemGroup { get; set; }

        public string UnitOfMeasure { get; set; }
```
Does not work:
```
        public ICollection<PurchaseItem> PurchaseItems { get; set; }

        public bool IsTrackedInInventory { get; set; }

        public int ItemGroupId { get; set; }
        public ItemGroup ItemGroup { get; set; }

        public bool IsPurchasedItem { get; set; }

        public string UnitOfMeasure { get; set; }
```

2. grid displays only one record, tried renaming some data in db and it shows the renames on refresh, but only one record, tried also the onBeforeSend ajax caching fix, still doesent work, also used debugger to verify I return multiple records in a list

3. decimal fields not rendered as decimal, or at all after specifically stating datatype="Number" in html

**Comment by AlekseyMartynov** [comment]
Hi @Se3ker 

> changing property order in class fixes it

This may indicate problems during JSON serialization of a response. E.g. attempt to serialize a self-referencing object structure.

Trace network requests in the browser developer tools (typically launched by F12 key)  and check if there are any failed ones related to data loading.

P.S. Ajax caching issue has been fixed in the current version, `onBeforeSend` fix is not needed anymore.

**Comment by AlekseyMartynov** [comment]
@Se3ker 
Have you had a chance to try my suggestions from the previous comment?
Feel free to re-open the ticket if you have more details.

**Comment by Se3ker** [comment]
There are still errors.
JSON serialization is messed up
Icons don't show anymore on sorting
Column chooser does not allow drop to grid of hidden column

Tried with a samples project but it does not compile

**Comment by AlekseyMartynov** [comment]
We'd like to help you resolve these issues.

> JSON serialization is messed up

Which kind of a problem you have with JSON? ASP.NET Core RTM introduced a breaking change related to naming conventions, we mentioned it in [release notes for 15.2.10](https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/releases/tag/15.2.10). Check https://github.com/aspnet/Announcements/issues/194.

> Icons don't show anymore on sorting
Column chooser does not allow drop to grid of hidden column

Please submit these items to the DevExpress Support channel: https://www.devexpress.com/Support/Center/Question/Create. A detailed steps to reproduce and a small sample project are greatly appreciated.

> Tried with a samples project but it does not compile

A similar problem has been reported recently. Try [this solution](https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/issues/36#issuecomment-229974146).
