### ISSUE TITLE
Controls do not render

### ISSUE THREAD

**Issue by Pelias2525** [DevExpress/DevExtreme.AspNet.TagHelpers#36]
I have installed Devextreme (16.1.4 or 15.2.10, it doesn't make a difference) and run the sample updated yesterday. None of the controls render; the markup is in the page source, but nothing renders. Is there something else that needs to happen in order to get the sample to render? The same thing occurs when I follow your directions to include the controls in my own project.

![controlinmarkup](https://cloud.githubusercontent.com/assets/7929055/16525427/33afed92-3f61-11e6-957c-0972b09f232c.JPG)
![nocontrolrendered](https://cloud.githubusercontent.com/assets/7929055/16525428/33b05bec-3f61-11e6-8aca-34470084f823.JPG)

**Comment by AlekseyMartynov** [comment]
Thanks for reporting this.

A quick tip:
* First, run the DevExtreme.AspNet.TagHelpers.Generator project
* Rebuild the whole solution
* Run Samples

Let me know whether the Sample project works after those steps.

**Comment by Pelias2525** [comment]
The control does render after I run the Generator project. Since I can't use the Nuget package (see other Issue reported) what files do I need to copy over if I am to include Devextreme.AspNet.TagHelpers in my own solution? Do I need to also grab the Generator project and include it in my own solution?

**Comment by AlekseyMartynov** [comment]
> what files do I need to copy over if I am to include Devextreme.AspNet.TagHelpers in my own solution? Do I need to also grab the Generator project and include it in my own solution?

There's no need to copy files or projects. Steps to setup a project for using DevExtreme Tag Helpers are described in https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/wiki/Install-Packages

P.S. Thanks, we'll look into the other issue you reported, too.

**Comment by Pelias2525** [comment]
Thanks, this was an attempt to sidestep the other issue; just trying to get something to render, even if it is a direct project reference. Hopefully the other issue can be resolved quickly so that I can start using this. Thanks for the excellent work and response time.

**Comment by AlekseyMartynov** [comment]
In fact, you have made a good point: currently it's not easy to run the Sample project, and VS tooling (still being in preview) has issues with reporting errors. We'll work on improving this aspect.

**Comment by San4es** [comment]
Improved via #42
