### ISSUE TITLE
Dependency specified was DevExtreme.AspNet.TagHelpers >= 15.2.10 but ended up with DevExtreme.AspNet.TagHelpers 0.0.

### ISSUE THREAD

**Issue by Pelias2525** [DevExpress/DevExtreme.AspNet.TagHelpers#37]
This occurs in the Samples project or my own project when specifying the Nuget Package referenced in the directions. It does not occur if I reference the project directly.
Steps to reproduce:
1) Open Sample
2) Open project.json in Samples project
3) Change project reference to Devextreme.AspNet.TagHelpers to the Nuget package referenced in the directions: "DevExtreme.AspNet.TagHelpers": "15.2.10"

![dependencyspecifiederror](https://cloud.githubusercontent.com/assets/7929055/16526275/43843526-3f65-11e6-8a40-f29a59e0a0fb.JPG)

**Comment by AlekseyMartynov** [comment]
It seems that specifying the `target` explicitly followed by running "Restore Packages" and  "Rebuild Solution" resolves the issue:

```
"DevExtreme.AspNet.TagHelpers": {
    "version": "15.2.10",
    "target": "package"
}
```

Can you confirm this?

**Comment by Pelias2525** [comment]
After a full rebuild I am able to get the sample to work. I am still having the same rendering issue with my own project; the markup is there and all of the steps in your instructions have been followed...but nothing is being displayed and there are no errors in the output while debugging. Below is the markup and result. The only other oddity that I can see is that I am using a different version of globalize (v1.1.1.) that contains a dist folder for distribution instead of a lib folder in your project (1.0.0). Could this be the source of the rendering problem? Is there something else that I can do to help troubleshoot?
Source:
![myprojectsource](https://cloud.githubusercontent.com/assets/7929055/16527966/87e9252e-3f6e-11e6-8275-85632bfb1ae7.JPG)

Output
![mysiterendered](https://cloud.githubusercontent.com/assets/7929055/16527968/8b46fed0-3f6e-11e6-9b05-bfe95cdf7004.JPG)

**Comment by Pelias2525** [comment]
In my project, Bower is reporting "Wrong Version" for jquery, even though I am only referencing 2.1.4, which is the same as the dependency requires. Also note the globalize dependency version. Thoughts?

Bower Dependencies for my site:
![mysitebowerdependencies](https://cloud.githubusercontent.com/assets/7929055/16528647/faec6f1e-3f72-11e6-94ac-c9dbeb0b1aa4.JPG)

Sample Bower Dependencies:
![samplebowerdependencies](https://cloud.githubusercontent.com/assets/7929055/16528660/0c7ec86c-3f73-11e6-87dd-f3bc14b270b3.JPG)

**Comment by Pelias2525** [comment]
Switching the bower package to 15.2.10 does resolves the bower issue, but results in nothing rendered as before.

![mysitebowerdependencies2](https://cloud.githubusercontent.com/assets/7929055/16528860/444838c2-3f74-11e6-8409-1f6838eb1061.JPG)

**Comment by AlekseyMartynov** [comment]
> Switching the bower package to 15.2.10 does resolves the bower issue

That's right. Versions of bower and NuGet packages must match. Providing Tag Helpers for 16.x is planned, but today we have only 15.2.

Ok, the next check is to ensure that [Tag Helpers are registered in _ViewImports](https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/wiki/Install-Packages#register-devextreme-aspnet-core-tag-helpers-assembly-and-namespace)

**Comment by Pelias2525** [comment]
I found the problem. I am using Areas and the _ViewImports file in the views area is apparently not consumed by any view in the Areas folder structure. I added _ViewImports to my Area's view folder and I'm finally rendering. For some reason the Intellisense is still not working for any views including those in the root Views folder. Thoughts?

**Comment by Pelias2525** [comment]
I have hit another snag. The tag is being interpretted at runtime and renders the grid. The load function is called and returns 13 rows. The grid renders the rows, but not the data...each cell is filled with nbsp. If I click on the filter button I can see that there is data...it's just not shown in the grid. Thoughts?

![rowsmissing](https://cloud.githubusercontent.com/assets/7929055/16530246/070c1b06-3f7c-11e6-89e4-4fbda2de3ad4.JPG)

![grid](https://cloud.githubusercontent.com/assets/7929055/16530249/09613f12-3f7c-11e6-9b9a-adf199cd8930.JPG)

![empty cells](https://cloud.githubusercontent.com/assets/7929055/16530355/958313d0-3f7c-11e6-9e84-e3f22d0b64b4.JPG)

**Comment by AlekseyMartynov** [comment]
It's caused by a recent breaking change in ASP.NET Core: https://github.com/aspnet/Announcements/issues/194

To resolve, use either lower camel case field names (`claimType` instead of `ClaimType`) or instructions for restoring previous naming strategy given in the mentioned announcement.

**Comment by Pelias2525** [comment]
Great, that works. Any thoughts on getting intellisense to work? 

What is the appropriate forum to ask about techniques to complete tasks not covered by the documentation at this point? For example, I'm going to need to use an EditForm instead of inline row editing, but see no documentation on how to do that with the new DevExtreme MVC suite or TagHelper syntax. Where is the appropriate place to ask such questions?

Thanks!

**Comment by Mehul** [comment]
Hi, about where to post questions, I'd recommend that you post them to our DevExpress support channel: https://www.devexpress.com/Support/Center/Question/Create

Thanks.
