### ISSUE TITLE
Tag Helper Updates Timeline

### ISSUE THREAD

**Issue by Pelias2525** [DevExpress/DevExtreme.AspNet.TagHelpers#38]
I would like to know roughly when/if the following will be updated:
- Update to DevExtreme 16.1 to support the current major build
- Additional Tag Helpers for

1. Forms / Editors
2. File Upload
3. Navigation including Tabs, Treeview, etc.

I would like to be an active tester of this functionality, but jumping back and forth between DevExtreme jquery (no MVC support), DevExtreme MVC Wrappers (no .NET Core Support), and Tag Helpers (very limited functionality and documentation) proves difficult.

**Comment by AlekseyMartynov** [comment]
> DevExtreme MVC Wrappers (no .NET Core Support)

Good news: several hours ago we published a set of .NET Core samples for DevExtreme ASP.NET MVC Wrappers: https://github.com/DevExpress/DevExtreme.AspNet.Mvc-Demos-NETCore

> Update to DevExtreme 16.1 to support the current major build
Additional Tag Helpers for...

I cannot give you any estimate time frames. Subscribe to our [ASP.NET blog](https://community.devexpress.com/blogs/aspnet/) to stay up to date with the latest MVC and ASP.NET Core related releases.
