### ISSUE TITLE
It is impossible to install the DevExtreme.AspNet.TagHelpers package from NuGet in an ASP.NET Core Web Application (.NET Framework)

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/DevExtreme.AspNet.TagHelpers#44]
I could not install the DevExtreme.AspNet.TagHelpers package from NuGet in an project created using the ASP.NET Core Web Application (.NET Framework) project template.

**Comment by Mehul** [comment]
@AlekseyMartynov Should this be part of that list of issues blog post?

**Comment by AlekseyMartynov** [comment]
No, it's our bug which we fix on our side.
