### ISSUE TITLE
Should target NET46 

### ISSUE THREAD

**Issue by tylerrbrown** [DevExpress/DevExtreme.AspNet.TagHelpers#46]
I've tested a build, and it seems to be simple to implement.

**Comment by AlekseyMartynov** [comment]
Duplicate of #44 

P.S. You are welcome to share your results via a pull request.
Thanks.

**Comment by tylerrbrown** [comment]
Done

On Aug 13, 2016, at 5:26 AM, AlekseyMartynov <notifications@github.com<mailto:notifications@github.com>> wrote:


Duplicate of #44<https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/issues/44>

P.S. You are welcome to share your results via a pull request.
Thanks.
