### ISSUE TITLE
Error load lib

### ISSUE THREAD

**Issue by ABurduli** [DevExpress/DevExtreme.AspNet.TagHelpers#51]
The type 'DataSourceLoadOptions' exists in both 'DevExtreme.AspNet.Mvc, Version=16.1.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' and 'DevExtreme.AspNet.TagHelpers, Version=15.2.11.0, Culture=neutral, PublicKeyToken=null'

**Comment by AlekseyMartynov** [comment]
Solved in https://github.com/DevExpress/DevExtreme.AspNet.TagHelpers/pull/50
