### ISSUE TITLE
Example of using datagrid validation-rules

### ISSUE THREAD

**Issue by jansokoly** [DevExpress/DevExtreme.AspNet.TagHelpers#52]
I cannot figure out nor can I find an example on how to use `validation-rules` with `dx-data-grid`. What's the syntax for that?

**Comment by AlekseyMartynov** [comment]
Hi,
validation rules can be assigned as follows:
```html
<dx-data-grid>
    <column validation-rules='new[] { new { type = "required", message = "..." } }' />
</dx-data-grid>
```

P.S. This project hasn't been updated for a while.
I suggest that you switch to using [DevExtreme ASP.NET Wrappers](https://js.devexpress.com/Documentation/Guide/ASP.NET_MVC_Wrappers/Fundamentals/). They are compatible with the most recent version of DevExtreme, have better integration with Razor markup, and can be used in .NET Core apps as well.
